config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/reddit/auth', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :private_messages, only: [:index, :new, :create]

  namespace 'api', path: '/api/v1' do
    get '/posts/r/', to: 'posts#index'
    get '/posts/title/', to: 'posts#title'
    get '/vote/:post_id/:vote_count', to: 'posts#update'
    get '/color_votes', to: 'posts#color'
  end
end

#add upvote and downvote links, send ajax requests to reddit with up and downvotes.  should
# update your page with some new css stuff.  If we refresh the new arrow color stays.
#POST /api/votevote

app/models/private_message.rb
class PrivateMessage

  def self.reddit_service
    RedditService.new
  end

  def self.all(mail_box, access_token)
    messages = JSON.parse(reddit_service.get(url: "https://oauth.reddit.com/",
                                              path: "message/#{mail_box}",
                                            token: access_token))

    messages["data"]["children"].map do |message_json|
      build_message(message_json["data"])
    end
  end

private

  def self.build_message(message_params)
    OpenStruct.new(message_params)
  end

end

app/controllers/private_messages_controller.rb
class PrivateMessagesController < ApplicationController
  def index
    session[:mail] = params[:mail]
    if selected_mailbox
      @messages = PrivateMessage.all(selected_mailbox, current_access_token)
      respond_to do |format|
        format.js
      end
    else
      @messages = PrivateMessage.all("inbox", current_access_token)
    end
  end
end

app/views/private_messages/_messages.html.erb
<% messages.each do |message| %>
  <h3>Sent by: <%= message.author.capitalize %></h3>
  <li>
    <%= message.body %>
  </li>
<% end %>

<% if messages.length == 0 %>
  <h3>Hmmm seems you don't have any mail in this box</h3>
<% end %>

app/views/private_messages/_new_message.html.erb
<%= form_for(new_message) do |f|%>

<% end %>

app/views/private_messages/_pm_nav.html.erb
<ul class="nav nav-tabs">
  <li></li>
  <li role="presentation" class="active"><%= link_to "Inbox", private_messages_path(mail: "inbox"), :remote => true %></li>
  <li role="presentation"> <%= link_to "Sent", private_messages_path(mail: "sent"), :remote => true %></li>
  <li role="presentation"> <%= link_to "Send a private message", new_private_message_path, :remote => true %> </li>
  <li role="presentation"> <%= link_to "Back to home page", root_path %></li>
</ul>

app/views/private_messages/index.html.erb
<div id="header">
  <h3 id="inbox">inbox</h3>
  <h3 id="sent" class="hide">sent</h3>
</div>

<ul id="aarons-messages">
  <%=  render partial: 'messages.html.erb', locals: {messages: @messages} %>
</ul>

<ul id="jordans-messages">
</ul>

<div id="new-message">
</div>